ConvertFrom-StringData -StringData @'
# Catalan strings
1=Esta herramienta requiere permisos de Administrador para ejecutarse.\nCerrando...
2=Comprobando ruta de instalación de Steam...
3=Carpeta de Steam encontrada en "{0}".
4=Carpeta de Steam no encontrada.
5=Se ha producido un error buscando la carpeta de Steam.
6=Escriba su ruta de localización de Steam.\n  Ejemplos:\n    %PROGRAMFILES(X86)%\\Steam\n    C:\\Program Files(x86)\\Steam\n    C:\\Games\\Steam\\\n\nPath
7=Ruta Seleccionada : "{0}"
8="config", "steamapps", "userdata", "steam.exe", "uninstall.exe" o "steam.signatures" no están presentes en la carpeta "{0}".
9=¿Quieres intentarlo otra vez?
10=1/2 - 1/6 - Cerrando Steam...
11=1/2 - 2/6 - Limpiando Steam...
12a=1/2 - 3/6 - Omitiendo. SecureBoot está habilitado.
12b=1/2 - 3/6 - Reestableciendo las opciones de inciales del PC...
13=1/2 - 4/6 - Compromprobando profundo de datos correuptos en WIndows...
14=1/2 - 5/6 - Arreglando la salud de Windows...
15=1/2 - 6/6 - Comprobando/Reparando el SO...
16=Programando tarea para la parte 2
17=Su PC esta a punto de reiniciarse. Salve cualquier cosa importante antes de continuar.\n\nPresione cualquier tecla cuando esté listo...
18=2/2 - 1/3 - Renovando IP y DNS...
19=2/2 - 2/3 - Reparando el Servicio de Steam...\nSteam se iniciará ahora.
20=Espere hasta que Steam se abra completamente, luego pulse cualquier botón...
21=2/2 - 3/3 - Actualizando Windows...
22=Gracias por usar este programa..\nRecuerde firmar mi perfil si le ha resultado útil.\n\nPresione cualquier tecla para continuar...
Part1=Parte 1/2
Part2=Parte 2/2
Yes=Sí
No=No
Bye=Por favor, vuelva cuando realmente quiera purgar Steam.
'@