ConvertFrom-StringData -StringData @'
# Spanish strings
1=Esta herramienta requiere permisos de Administrador para ejecutarse.\nCerrando...
2=Comprobando ruta de instalación de Steam...
3=Carpeta de Steam encontrada en "{0}".
4=Carpeta de Steam no encontrada.
5=Se ha producido un error buscando la carpeta de Steam.
6=Escriba su ruta de localización de Steam.\n  Ejemplos:\n    %PROGRAMFILES(X86)%\\Steam\n    C:\\Program Files(x86)\\Steam\n    C:\\Games\\Steam\\\n\nPath
7=Ruta Seleccionada : "{0}"
8="config", "steamapps", "userdata", "steam.exe", "uninstall.exe" or "steam.signatures" are not present in the folder "{0}".
9=Would you like to try again?
10=1/2 - 1/6 - Closing Steam...
11=1/2 - 2/6 - Cleaning Steam...
12=1/2 - 3/6 - Resetting PC start options to default...
13=1/2 - 4/6 - Deep Checking Windows for corrupted data...
14=1/2 - 5/6 - Fixing Windows Health...
15=1/2 - 6/6 - Checking/Repairing OS...
16=Scheduling task for Part 2
17=Your pc is going to be restarted. Save anything important before continuing.\n\nPress any key when you are ready...
18=2/2 - 1/3 - Renewing IP and DNS...
19=2/2 - 2/3 - Repairing Steam Service...\nSteam will start now.
20=Wait till steam opens completely, then press any buttons...
21=2/2 - 3/3 - Updating Windows...
22=Thanks for using this program.\nRemember to sign my profile if it was useful.\n\nPress any key when you are ready...
Part1=Part 1/2
Part2=Part 2/2
Yes=Yes
No=No
Bye1=Bye bye.
Bye2=Please, came again once you really want to refresh Steam.
Title=Steam Cleaner By Apryed - v0.1_17-01-2025
'@