ConvertFrom-StringData -StringData @'
# Spanish strings
1=Esta herramienta requiere permisos de Administrador para ejecutarse.\nCerrando...
2=Comprobando ruta de instalación de Steam...
3=Carpeta de Steam encontrada en "{0}".
4=Carpeta de Steam no encontrada.
5=Se ha producido un error buscando la carpeta de Steam.
6=Escriba su ruta de localización de Steam.\n  Ejemplos:\n    %PROGRAMFILES(X86)%\\Steam\n    C:\\Program Files(x86)\\Steam\n    C:\\Games\\Steam\\\n\nPath
7=Ruta Seleccionada : "{0}"
8="steam.exe", "uninstall.exe" or "GameOverlayUI.exe" are not present in the folder "{0}".
9=Would you like to try again?
10=1/2 - 1/6 - Closing Steam...
11=1/2 - 2/6 - Cleaning Steam...
12=1/2 - 3/6 - Resetting PC start options to default...
13=1/2 - 4/6 - Deep Checking Windows for corrupted data...
14=1/2 - 5/6 - Fixing Windows Health...
15=1/2 - 6/6 - Checking/Repairing OS...
16=Scheduling task for Part 2
17=2/2 - 1/3 - Renewing IP and DNS...
18=2/2 - 2/3 - Repairing Steam Service...\nSteam will start now.
19=2/2 - 3/3 - Updating Windows...
20=Thanks for using this program.\nRemember to sign my profile IF it was useful.\nPress any key to quit.

Part1=Parte 1/2
Part2=Parte 2/2
Yes=Sí
No=No
Bye1=Bye bye.
Bye2=Please, came again once you really want to refresh Steam.
'@